apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rabbitmq-server-0
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 30Gi
  hostPath:
    path: /mnt/rabbitmq-server-0
    type: Directory
  persistentVolumeReclaimPolicy: Retain