apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: rabbitmq
  namespace: monitoring
spec:
  podMetricsEndpoints:
  - interval: 15s
    port: prometheus
    path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/component: rabbitmq
  namespaceSelector:
    any: true